spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roadmap_project
    username: group37
    password: password
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


logging.level.org:
  hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
  springframework.jdbc.core:
    JdbcTemplate: DEBUG
    StatementCreatorUtils: TRACE