spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roadmapProject
    username: group37
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

